### ISSUE TITLE
Access to found items and preventing display of found items

### ISSUE THREAD

**Issue by ammark47** [StevenIseki/react-search#13]
Hi,
I would like to use the items found in the search bar and send them as props to a different component. Is there anyway I can get access to the these found items.

Also, I would like to prevent displaying these items. is that possible?

**Comment by StevenIseki** [comment]
Hi, for preventing displaying the items you could easily do that with css

```css
.react-search__menu {
  display: none;  
}
```

For passing the found items to another component, the items are stored as `state.matchingItems` I may make an update so that the onChange callback passes back the matching items, which might help for this case.

**Comment by ammark47** [comment]
Awesome! The css worked :) and I tried fiddling with passing matchingItems back to the call back but I couldn't figure out how to get it to work. 

Btw, the passing it to the callback would be perfect for my use case. Thanks :)

**Comment by StevenIseki** [comment]
Update now version 1.0.8 passes the results along with the event back to the callback.
You can see an example of how to setup the callback to pass in the matching results in the [example](https://github.com/StevenIseki/react-search/blob/master/example/example.js).

Thanks,
Steven
