### ISSUE TITLE
npm install not working on 1.0.8

### ISSUE THREAD

**Issue by ammark47** [StevenIseki/react-search#14]
Hi, Sorry about opening another issue but npm install is not working on the latest version for this. this is my debug log:
Ammars-MBP:recoveryBall AmmarKarim$ npm install react-search --save

> react-search@1.0.8 postinstall /Users/AmmarKarim/Desktop/backUps/recoveryBall/node_modules/react-search
> npm run build

> react-search@1.0.8 build /Users/AmmarKarim/Desktop/backUps/recoveryBall/node_modules/react-search
> babel src --out-dir lib

The CLI has been moved into the package `babel-cli`. See http://babeljs.io/docs/usage/cli/

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/Users/AmmarKarim/Desktop/backUps/recoveryBall/node_modules/.bin/npm" "run" "build"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-search@1.0.8 build: `babel src --out-dir lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-search@1.0.8 build script 'babel src --out-dir lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AmmarKarim/Desktop/backUps/recoveryBall/node_modules/react-search/npm-debug.log
npm WARN EPACKAGEJSON homepage@1.0.0 No description
npm WARN EPACKAGEJSON homepage@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-search" "--save"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! react-search@1.0.8 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-search@1.0.8 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AmmarKarim/Desktop/backUps/recoveryBall/npm-debug.log

**Comment by StevenIseki** [comment]
Thanks for testing this and pointing it out. Yes that was my mistake, some confusion with a post-install and pre-publish script for the module which I didn't add and was a bit unnecessary as I can just include the lib and src, it is simpler. It should be all good now latest version 1.0.9

Please let me know how it goes, it is working nicely for me

Thanks,
Steven

**Comment by ammark47** [comment]
works perfectly :)
